from .Graficos import Graficos

# Parámetros generales del menú
MAX_OPCIONES_VISIBLES = 8
NUMERO_FILAS_MENU = 4
NUMERO_COLUMNAS_MENU = 2

# Tamaños de celda
ALTURA_GENERAL_CELDA = 5

ANCHO_CELDA_RECTANGULAR = 28
ALTO_CELDA_RECTANGULAR = ALTURA_GENERAL_CELDA

ANCHO_CELDA_NUMERICA = 12
ALTO_CELDA_NUMERICA = ALTURA_GENERAL_CELDA

ANCHO_CELDA_FLECHA = 24
ALTO_CELDA_FLECHA = ALTURA_GENERAL_CELDA

ESPACIO_ENTRE_FILAS_MENU = 1
ESPACIO_ENTRE_COLUMNAS_MENU = 2

ALTURA_CELDA_ACCION = (ALTURA_GENERAL_CELDA + ESPACIO_ENTRE_FILAS_MENU) * NUMERO_FILAS_MENU - ESPACIO_ENTRE_FILAS_MENU * 2
ANCHO_CELDA_ACCION = ANCHO_CELDA_RECTANGULAR * 2 + ESPACIO_ENTRE_COLUMNAS_MENU

# Instancias de gráficos
GRAFICOS_CELDA_RECTANGULAR = Graficos(ANCHO_CELDA_RECTANGULAR, ALTO_CELDA_RECTANGULAR)
GRAFICOS_CELDA_NUMERICA = Graficos(ANCHO_CELDA_NUMERICA, ALTO_CELDA_NUMERICA)
GRAFICOS_CELDA_FLECHA = Graficos(ANCHO_CELDA_FLECHA, ALTO_CELDA_FLECHA)
GRAFICOS_CELDA_ACCION = Graficos(ANCHO_CELDA_ACCION, ALTURA_CELDA_ACCION)

# Celdas construidas
CELDA_RECTANGULAR = GRAFICOS_CELDA_RECTANGULAR.crear_celda_rectangular()
CELDA_RECTANGULAR_VACIA = GRAFICOS_CELDA_RECTANGULAR.crear_celda_rectangular_vacia()

CELDA_NUMERICA = GRAFICOS_CELDA_NUMERICA.crear_celda_numerica()
CELDA_NUMERICA_VACIA = GRAFICOS_CELDA_NUMERICA.crear_celda_numerica_vacia()

CELDA_FLECHA_IZQUIERDA = GRAFICOS_CELDA_FLECHA.crear_celda_flecha_izquierda()
CELDA_FLECHA_DERECHA = GRAFICOS_CELDA_FLECHA.crear_celda_flecha_derecha()
CELDA_FLECHA_VACIA = GRAFICOS_CELDA_FLECHA.crear_celda_flecha_vacia()

CELDA_ACCCION = GRAFICOS_CELDA_ACCION.crear_celda_rectangular()